{{- if .Values.mailrelay.enabled }}

{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "froxlor.fullname" . }}-mailrelay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "froxlor.fullname" . }}
      component: mailrelay
  template:
    metadata:
      labels:
        app: {{ include "froxlor.fullname" . }}
        component: mailrelay
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
      - name: mailrelay
        image: {{ .Values.mailrelay.image.repository }}:{{ .Values.mailrelay.image.tag }}
        imagePullPolicy: {{ .Values.froxlor.image.pullPolicy }}
        env:
        - name: MAIL_HOSTNAME
          value: "{{ required "mailrelay.hostname" .Values.mailrelay.hostname }}"
        {{ if .Values.smarthost.host }}
        - name: SMARTHOST 
          value: {{ .Values.smarthost.host }}
        {{ end }}  
        {{ if .Values.smarthost.port }}
        - name: SMARTHOST_PORT
          value: {{ .Values.smarthost.port }}
        {{ end }}
        {{ if .Values.smarthost.tls.enabled }}
        - name: SMARTHOST_TLS
          value: {{ .Values.smarthost.tls.enabled }}
        {{ end }}
        {{ if .Values.smarthost.username }}
        - name: SMARTHOST_USERNAME 
          value: {{ .Values.smarthost.username }}
        {{ end }}
        {{ if .Values.smarthost.password }} 
        - name: SMARTHOST_PASSWORD 
          value: {{ .Values.smarthost.password }}
        {{ end }}
        livenessProbe:
          tcpSocket:
            port: 25
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 25
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
        volumeMounts:
        - name: data
          subPath: mailrelay-spool
          mountPath: /var/spool/exim
        - name: data
          subPath: log
          mountPath: /var/log
        ports:
        - name: smtp
          containerPort: 25
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "froxlor.fullname" . }}-storage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "froxlor.fullname" . }}-mailrelay
  labels:
    app: {{ include "froxlor.fullname" . }}
    component: mailrelay
spec:
  selector:
    app: {{ include "froxlor.fullname" . }}
    component: mailrelay
  ports:
  - name: smtp
    port: 25
    protocol: TCP
{{- end }}