{{ if .Values.phpmyadmin.enabled }}

{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "froxlor.fullname" . }}-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "froxlor.fullname" . }}
      component: phpmyadmin
  template:
    metadata:
      labels:
        app: {{ include "froxlor.fullname" . }}
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: {{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag }}
        imagePullPolicy: {{ .Values.phpmyadmin.image.pullPolicy }}
        env:
          - name: PMA_HOST
            value: "{{ include "froxlor.fullname" . }}-mysql"
          - name: HIDE_PHP_VERSION
            value: "true"
          - name: UPLOAD_LIMIT
            value: 100m
          - name: PMA_ABSOLUTE_URI
            value: "https://localhost/phpmyadmin/"
        ports:
          - name: phpmyadmin
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: phpmyadmin
          periodSeconds: 5
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: phpmyadmin
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "froxlor.fullname" . }}-phpmyadmin
  labels:
    app: {{ include "froxlor.fullname" . }}
    component: phpmyadmin
spec:
  selector:
    app: {{ include "froxlor.fullname" . }}
    component: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 80
    protocol: TCP

{{ end }}
