nameOverride: ""
fullnameOverride: ""

# set hostIP to bind all docker container to one specified IP 
# - helpful if on one host should also reside some other (kubernetes) services
# - second IP on host must exist 
# - ensure that all other deployments are bind to an ip explicitly
hostIP: {} 

persistence:
  size: 100Gi
  type: hostPath
  # storageClass: default
#  hostPath: /path/on/the/host


mysql:
  enabled: true
  image:
    repository: library/mariadb
    tag: 10.4.15
    pullPolicy: IfNotPresent
  database: froxlor
  user: froxlor
  #password:  Chang3m3!
  #rootPassword: Chang3m3!

froxlor:
  image:
    repository: quay.io/evermind/froxlor
    tag: master
    pullPolicy: Always

mailrelay:
  enabled: false
  image:
    repository: micwy/docker-alpine-exim-mailrelay
    tag: 1.0.4
    pullPolicy: Always
  # hostname: helo-hostname for outgoing mails


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
